import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // baseSidebar: [
    // {type: 'autogenerated', dirName: '.'},
  // ],
  recipesSidebar: [ { type: 'autogenerated', dirName: 'recipes' } ],
  plantsSidebar: [ { type: 'autogenerated', dirName: 'plants' } ],
  miscSidebar: [ { type: 'autogenerated', dirName: 'misc' } ],
  guidesSidebar: [ { type: 'autogenerated', dirName: 'guides' } ],
};

export default sidebars;
